version: '3.9'
services:
  app:
    ports:
      - 8080:80
    image: mabizard/app-armovies:v1
    networks:
      - armovies
    deploy:
      replicas: 4
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure

  db:
    image: mabizard/mariadb:10.7.8
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: "armovies"
    secrets:
      - mysql_root_password
    networks:
      - armovies
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      update_config:
        delay: 5s
      restart_policy:
        condition: on-failure

  lb:
    ports:
      - 80:80
      - 8404:8404
    image: mabizard/haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    dns: 127.0.0.11
    networks:
      - armovies
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s

secrets:
  mysql_root_password:
    external: true

networks:
  widan:
    driver: overlay

volumes:
  db_data:
